### ISSUE TITLE
Error in installing Polybar 3.4.3-1 on Ubuntu 18.04 

### ISSUE THREAD

**Issue by pvonmoradi** [regolith-linux/speed-ricer#17]
`sudo apt update && sudo apt upgrade` reports that one package is upgradable (polybar) but upon upgrading, it complains about lack of dependencies. Is the package built for 18.04? 
```
$ sudo apt install polybar 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 polybar : Depends: libc6 (>= 2.29) but 2.27-3ubuntu1.2 is to be installed
           Depends: libgcc-s1 (>= 3.0) but it is not installable
           Depends: libstdc++6 (>= 9) but 8.4.0-1ubuntu1~18.04 is to be installed
           Depends: python3-xcbgen but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by moritzheiber** [comment]
Which version of Regolith are you using? We only provide support for Regolith users, otherwise the packages in this repository are "take it or leave it" I'm afraid.

**Comment by pvonmoradi** [comment]
@moritzheiber 
I'm not using Regolith but since Regolith is based on Ubuntu, I think it would be problematic for that users also. Basically the version in Bionic is built for Focal. http://i.imgur.com/eeynzah.png

**Comment by rehashedsalt** [comment]
That version is *supposed* to be Focal-only because Polybar >=3.4 hard depends on `python3-xcbgen` (Python 2 is not supported), which is only packaged in Focal. Backporting to Bionic will also require backporting `python3-xcbgen`. I guess Ken wasn't aware when he copied the package over.

[The main Regolith PPA does not have this package](https://launchpad.net/~regolith-linux/+archive/ubuntu/stable), so odds are Polybar is broken on Regolith Bionic installations, too. I'll spin up a VM and test real quick.

cc @moritzheiber @kgilmer

**Comment by kgilmer** [comment]
> I guess Ken wasn't aware when he copied the package over.

This is true.  It's almost certain that someone asked for an updated Bionic version of polybar months back and I simply used the copy function in launchpad to copy the release from `focal` to `bionic` without looking into it.

FWIW, speed-ricer is intended to be a separate project from Regolith.  The idea is to provide packages that are not available in Ubuntu repositories as a general service to users, but at the time I was not really aware of the standard way packages should get into Ubuntu Universe.  Also, the "mono-repo" approach to staging package metadata is not   I've somewhat given up on speed-ricer due to these issues.  Mainly I'd like to get to the point of being a MOTD so I can push package updates for all of the Ubuntu community but my work on Regolith always takes priority so I just haven't made that happen yet.

I'll remove the invalid Bionic package for Polybar so others don't have to spin their wheels trying to debug it, and thanks for all the detailed bug reports.

**Comment by kgilmer** [comment]
```
Source and binaries deleted by Ken Gilmer:
polybar 3.4.3-1ubuntu1 in bionic

Deletion comment: None
```

I've removed the offending package.  FYI I won't have time to look into this further, but if someone else submits a PR to properly package Polybar on Bionic I would be happy to take it and build the result in the the speed-ricer PPA.
